[package]
name = "climbingTheHill"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
vulkano-util = "0.34.1"
vulkano-win = "0.34.0"
winit = "0.30.7"
pub-fields = "0.1.1"

[profile.dev]
opt-level = 1